version: "3.8"

services:
  vapor-app:
    build: .
    container_name: vapor-docker-example
    ports:
      - "8080:8080"
    environment:
      # Must match with what is being used in configure.swift
      PORT: "8080"
      HOSTNAME: "0.0.0.0"
    restart: unless-stopped